spring.application.name=like-hero-to-zero

spring.datasource.url=jdbc:mysql://localhost:3306/like_hero_to_zero
spring.datasource.username=likehero_app
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true